geo_app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('register.urls')),
    path('', include('shops.urls'))
]

register/urls.py
from django.urls import path, include
from . import views

app_name = 'register'

urlpatterns = [
    path('register', views.ChooseUserTypeView.as_view(), name='choose-type'),
    path('register/user', views.RegisterAsUser.as_view(), name='as-user'),
    path('register/shop-owner', views.RegisterAsShopOwner.as_view(), name='as-shop-owner'),
    path('', include('django.contrib.auth.urls')),
]

shops/urls.py
from django.urls import path, include
from . import views

app_name = 'shops'
urlpatterns = [
    path('', views.home, name='welcome'),
    path('close-by', views.ShopsCloseToUser.as_view(), name='close-by'),
    path('management/', include([
        path('create', views.ShopCreate.as_view()),
    ])),
]

register/models.py
from django.db import models

# Create your models here.

shops/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.gis.db import models as geoModels
from django.db import models


# Create your models here.

class User(AbstractUser):
    """User types"""
    SHOP_OWNER = 'shop_owner'
    SHOP_USER = 'shop_user'
    SHOP_ADMIN = 'admin'

    USER_TYPE_CHOICES = (
        {1, SHOP_USER},
        {2, SHOP_OWNER},
        {3, SHOP_ADMIN},
    )

    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=1)

    def __str__(self):
        return self.username

    def is_shop_owner(self):
        return self.user_type == 2


class Shop(models.Model):
    name = models.CharField(max_length=100)
    location = geoModels.PointField(srid=32140)
    street_address = models.CharField(max_length=255, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from shops.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

register/views.py
from django.conf import settings
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView
from shops.models import User
from .forms import RegisterForm


# Create your views here.

class ChooseUserTypeView(TemplateView):
    template_name = 'registration/choose_type.html'


class RegisterAsUser(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'registration/register.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = User.SHOP_USER
        kwargs['title'] = 'Register as user'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.user_type = 1
        user.save()
        login(self.request, user)
        return redirect('/')


class RegisterAsShopOwner(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'registration/register.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = User.SHOP_OWNER
        kwargs['title'] = 'Register as shop owner'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.user_type = 2
        user.save()
        login(self.request, user)
        return redirect('/')

shops/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.gis.measure import D
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.contrib.gis.geos import fromstr, Point, GEOSGeometry
from django.contrib.gis.db.models.functions import Distance
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, TemplateView
from .models import Shop


# Create your views here.

def home(request: HttpRequest):
    return render(request, 'shops/welcome.html')


longitude, latitude = 7.9709675, 5.0280591

user_location = GEOSGeometry(f'POINT({longitude} {latitude})', srid=4326)
# user_location = Point(longitude, latitude, srid=4326)


@method_decorator([login_required, user_passes_test(lambda u: u.user_type == 1)], name='dispatch')
class ShopsCloseToUser(ListView):
    model = Shop
    context_object_name = 'shops'
    queryset = Shop.objects.filter(location__distance_lte=(user_location, D(m=1)))
    template_name = 'shops/user_shops.html'


class ShopCreate(CreateView):
    model = Shop
    template_name = 'shops/manage/create.html'
    fields = ['name', 'location', 'street_address']

register/templates/register/register.html
{% extends "layouts/base.html" %}

{% block title %}Create an Account{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card card-login mb-3">
        <div class="card-header card-header-primary text-center">
            <h4 class="card-title">
                <strong>Select an account type</strong>
            </h4>
        </div>
        <div class="card-body">
            <form method="POST" class="form-group">
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-success">Register</button>
            </form>
            <div class="row">
                <div class="col-6">
                    <a href="{% url 'login' %}" class="text-light">
                        <small>
                            Register
                        </small>
                    </a>
                </div>
                <div class="col-6 text-right"></div>
            </div>
        </div>
    </div>
{% endblock %}

shops/templates/shops/layouts/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Geo SHop</title>

    <!-- Scripts -->
    <script src="{% static 'js/core/jquery.min.js' %}" defer=""></script>
    <script src="{% static 'js/core/popper.min.js' %}" defer></script>
    <script src="{% static 'js/core/bootstrap.min.js' %}" defer></script>

    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link href="{% static 'css/material-dashboard.min.css' %}" rel="stylesheet">

</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Goe Shops</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'shops:welcome' %}">Home</a>
                    {% if  user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'register:logout' %}">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'register:choose-type' %}">Register</a>
                    <a class="nav-item nav-link" href="{% url 'register:login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<main role="main">

    {% block content %}
    {% endblock %}
{% comment %}    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Album example</h1>
            <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator,
                etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
            <p>
                <a href="#" class="btn btn-primary my-2">Main call to action</a>
                <a href="#" class="btn btn-secondary my-2">Secondary action</a>
            </p>
        </div>
    </section>

    <div class="album py-5 bg-light">

    </div>{% endcomment %}

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
    </div>
</footer>
</body>
</html>

shops/templates/shops/user_shops.html
{% extends 'shops/layouts/base.html' %}

{% block content %}
    <div class="col-md-8 offset-md-2 bg-light shake p-4">
        <h1>Nearby Shops</h1>
        {% if shops %}
            {% for shop in shops %}
                <li class="list-group-item">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">
                            {{ shop.name }}
                        </h5>
                    </div>
                    <p class="mb-1">
                        Address: {{ shop.street_address }}
                    </p>
                    <small>Distance: {{ shop.distance }}</small>
                </li>
            {% endfor %}
        {% else %}
            <p class="text-center">
                No Shops close by.
            </p>
        {% endif %}
    </div>
{% endblock %}

shops/templates/shops/welcome.html
{% extends 'shops/layouts/base.html' %}
{% block content %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">
                Geo Shop
            </h1>
            <p class="lead text-muted">
                Find Shops around you. For shop owners, make your business visible to the
                audience who would respond the most
            </p>
            <p>
                {% if user.is_authenticated %}
                    {% if user.is_shop_owner %}
                    <a href="#" class="btn btn-primary my-2">Manage Shops</a>
                    {% else %}
                        <a href="{% url 'shops:close-by' %}" class="btn btn-primary my-2">
                            View Shops Close By
                        </a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'register:as-user' %}" class="btn btn-primary my-2">Register as User</a>
                    <a href="{% url 'register:as-shop-owner' %}" class="btn btn-secondary my-2">Register as Shop Owner</a>
                {% endif %}
            </p>
        </div>
    </section>
{% endblock %}

templates/layouts/base.html
{% load static %}
<!doctype html>
<html lang="en-gb">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Scripts -->
    <script src="{% static 'js/core/jquery.min.js' %}" defer=""></script>

    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link href="{% static 'css/material-dashboard.min.css' %}" rel="stylesheet">

    <title>Shops</title>
    <style>
        .wrapper {
            height: auto;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top text-white" type="log">
    <div class="container">
        <div class="navbar-wrapper">
            <a href="{% url 'shops:welcome' %}" class="navbar-brand">Home</a>
        </div>
    </div>
</nav>
    <div class="wrapper wrapper-full-page">
        <div class="page-header login-page header-filter login-bg">
            <div class="container" style="height: auto;">
                <div class="row align-items-center">
                    <div class="col-lg-4 col-md-6 col-sm-8 mx-auto">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>